backend:
  name: git-gateway # Or 'github' if using GitHub
  branch: production # Git branch to commit changes
  auth_scope: repo

media_folder: "images/uploads" # Media files saved relative to /public
public_folder: "/images/uploads" # Public URL for media files

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog" # Path in your Git repo for storing blog posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: true }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
